-- Create Profiles Table
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  status text default 'Available',
  location text default 'Unknown',
  coordinates jsonb, -- {lat: 0, lng: 0}
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Create Messages Table
create table public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.messages enable row level security;

-- Create Policies
-- Allow anyone (authenticated or not for now, or just authenticated) to read profiles
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

-- Allow users to insert their own profile
create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

-- Allow users to update their own profile
create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Allow all authenticated users to read messages
create policy "Authenticated users can read messages." on public.messages
  for select using (auth.role() = 'authenticated');

-- Allow authenticated users to insert messages
create policy "Authenticated users can insert messages." on public.messages
  for insert with check (auth.role() = 'authenticated');

-- Enable Realtime
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.messages;
